general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    cloudFoundry:
        org: '5955a6d8trial'
        space: 'dev'
        credentialsId: 'e177a86e-719a-43d0-bfa3-742ed56c94b0'
